server:
  port: 9080
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      #druid 监控配置
      stat-view-servlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        # 控制台管理用户名和密码
        login-username: root
        login-password: 123
       
    dynamic:
      primary: db1 #配置默认数据库
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        db1: # 数据源1配置
          url: jdbc:postgresql://127.0.0.1:5432/postgres
          username: postgres
          password: Pass1324
          driver-class-name: org.postgresql.Driver
          druid:
             initial-size: 5
             min-idle: 5
             max-active: 20
             max-wait: 6000
        db2: # 数据源2配置
          url: jdbc:postgresql://127.0.0.1:5432/pg2
          username: postgres
          password: Pass1324
          driver-class-name: org.postgresql.Driver
          druid:
             initial-size: 5
             min-idle: 5
             max-active: 20
             max-wait: 6000
  autoconfigure:
    exclude:  com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure # # 去除druid配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 